noun =input('Choose  a noun')
p_noun=input('Choose a plural noun')
noun2 =input('Choose  a noun')
place=input('name a place')
adjective=input('Choose an adjective')
noun3=input('choose a noun')
print('-------------------------------------------------------------')
print('be kind to your ',noun, '-footed',p_noun)
print('For a duck may be somebody\'s',noun2,',')
print('be kind to your ',p_noun, '-footed',place)
print('Where the weather is always',adjective,'.\n')
print('You may think that this is the',noun3,',')
print('Well it is.')
print('--------------------------------------------------------------')
